### ISSUE TITLE
Can't set custom notification icon

### ISSUE THREAD

**Issue by andrijans** [360dialog/sample-app-android#2]
I can't set custom notification icon. I added meta-data in manifest also I tried with custom decorator but no luck. I always get the application icon shown on statusbar

**Comment by wkukielczak** [comment]
Hi @andrijans!

I assume that's because you try to send the similar push notification manually to your compiled app:
```json
{
    "to": "--- YOUR PUSH TOKEN ---",
    "notification": {
        "title": "Hi there!",
        "body": "Tap to open the app"
    }
}
```
If that's true, then it would not work, as the tag
```xml
<meta-data android:name="com.threesixtydialog.sdk.notification_icon"
    android:resource="--- YOUR ICON ---" />
```
is supposed to work only for 360dialog's notifications, which are sent using different payload, like:
```json
{
    "to": "--- YOUR PUSH TOKEN ---",
    "data": {
        "d360": {
            "tr": {
                "pid": "--- UNIQUE STRING ---"
            },
            "notification": {
                "title": "Hi there!",
                "body": "Tap to open the app"
            }
        }
    }
}
```
Note that you can test 360dialog's notifications using the SDK tester you can find here: https://github.com/360dialog/sdk-tester-android (this tester is also a sub-module of this repository)

In order to configure custom icon for FCM system notifications youy need to add another `<meta-data>` element in `AndroidManifest.xml`:

```xml
<meta-data android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="--- YOUR ICON ---" />
```
for details, see: https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest

Note: you can keep both `<meta-data>` tags together in your manifest

**Comment by JanC** [comment]
Hi @andrijans 
we do not provide support via Github issues. If the above solution does not help, please contact our integration team at support@360dialog.com

cheers,
